# Python Tools, Getting to know your Data, Filteration, and Visualization

## 1. Import the necessary libraries

In [22]:
import pandas as pd
import matplotlib as plt
import seaborn as sb

## 2. Import the chipotle dataset

In [23]:
path = 'chipotle.tsv'
chipo = pd.read_csv(path, sep = '\t')

## 3. Load the dataset and display the first 5 rows.

In [24]:
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

## 4. How many rows and columns does the dataset have?

In [25]:
chipo.shape

(4622, 5)

## 5. What are the column names in the dataset?

In [26]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

## 6. How is the dataset indexed?

In [27]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

## 7. Which columns are categorical and which are numerical?

In [28]:
categorical_cols = chipo.select_dtypes(include = "object").columns
numerical_cols = chipo.select_dtypes(exclude = "object").columns

print(categorical_cols)
print(numerical_cols)

Index(['item_name', 'choice_description', 'item_price'], dtype='object')
Index(['order_id', 'quantity'], dtype='object')

## 8. Why is item_price not considered numerical?

In [29]:
chipo['item_price'].head() #item_price is continuous value

0     $2.39
1     $3.39
2     $3.39
3     $2.39
4    $16.98
Name: item_price, dtype: object

## 9. Convert item_price to a numerical (float) column

In [30]:
chipo['item_price'] = chipo['item_price'].str.replace('$', ' ').astype(float)

chipo['item_price'].dtype

In [31]:
chipo['item_price'].head()

0     2.39
1     3.39
2     3.39
3     2.39
4    16.98
Name: item_price, dtype: float64

## 10. Show basic statistics for numerical columns

In [32]:
chipo.describe()

          order_id     quantity   item_price
count  4622.000000  4622.000000  4622.000000
mean    927.254868     1.075725     7.464336
std     528.890796     0.410186     4.245557
min       1.000000     1.000000     1.090000
25%     477.250000     1.000000     3.390000
50%     926.000000     1.000000     8.750000
75%    1393.000000     1.000000     9.250000
max    1834.000000    15.000000    44.250000

<h2 align = center>Sorting and Filtering Data</h2>

## 11. How many products cost more than $10.00?

In [33]:
chipo[chipo.item_price > 10.00]['order_id'].count()

np.int64(1130)

In [34]:
# size measures total entries, while count() measures valid (non-null) entries.

## 12.What is the price of each item?

In [39]:
chipo[['item_name', 'item_price']]

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

## 13.Sort the dataset by the item name

In [40]:
chipo.item_name.sort_values()

3389    6 Pack Soft Drink
341     6 Pack Soft Drink
1849    6 Pack Soft Drink
1860    6 Pack Soft Drink
2713    6 Pack Soft Drink
              ...
2384    Veggie Soft Tacos
781     Veggie Soft Tacos
2851    Veggie Soft Tacos
1699    Veggie Soft Tacos
1395    Veggie Soft Tacos
Name: item_name, Length: 4622, dtype: object

## 14. What is the quantity of the most expensive item ordered?

In [43]:
chipo.item_price.sort_values(ascending = False).head(1)

3598    44.25
Name: item_price, dtype: float64

## 15. How many times was a Veggie Salad Bowl ordered?

In [47]:
chipo[chipo.item_name == 'Veggie Salad Bowl']['quantity'].sum()

np.int64(18)

## 16. How many times did someone order more than one Canned Soda?

In [55]:
chipo[(chipo.item_name == 'Canned Soda') & (chipo.quantity > 1)]['quantity'].count()

np.int64(20)

## 17. How many different products are sold?

In [50]:
unique_products = chipo['item_name'].nunique()
print(unique_products)

50

## 18. What is the total revenue?

In [59]:
total_revenue = (chipo['item_price']* chipo['quantity']).sum()
print(total_revenue)

39237.02

## 19. What is the average price of items?

In [62]:
avg_price = chipo['item_price'].mean()
print(avg_price)

7.464335785374297

## 20. How many orders were made in total?

In [66]:
total_number_orders = chipo['order_id'].nunique()
print(total_number_orders)

1834

## 21. What is the total quantity of items ordered?

In [67]:
total_quantity = chipo['quantity'].sum()
print(total_quantity)

4972

## 22. Which item has the highest average price?

In [68]:
chipo.groupby('item_name')['item_price'].mean().idxmax()

'Bowl'

## 23. How many items include “Chicken” in their name?

In [69]:
chipo[chipo['item_name'].str.contains('Chicken')]['item_name'].count()

np.int64(1560)

## 24. Which item was the most-ordered item?

In [70]:
chipo.groupby('item_name')['quantity'].sum().idxmax()

'Chicken Bowl'

## 25. Group the dataset by item_name and count how many times each product appears.

In [72]:
chipo.groupby('item_name').size().sort_values(ascending = False)

item_name
Chicken Bowl                             726
Chicken Burrito                          553
Chips and Guacamole                      479
Steak Burrito                            368
Canned Soft Drink                        301
Steak Bowl                               211
Chips                                    211
Bottled Water                            162
Chicken Soft Tacos                       115
Chicken Salad Bowl                       110
Chips and Fresh Tomato Salsa             110
Canned Soda                              104
Side of Chips                            101
Veggie Burrito                            95
Barbacoa Burrito                          91
Veggie Bowl                               85
Carnitas Bowl                             68
Barbacoa Bowl                             66
Carnitas Burrito                          59
Steak Soft Tacos                          55
6 Pack Soft Drink                         54
Chips and Tomatillo Red Chili Salsa       48
Chicken Crispy Tacos                      47
Chips and Tomatillo Green Chili Salsa     43
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        35
Chips and Tomatillo-Green Chili Salsa     31
Steak Salad Bowl                          29
Nantucket Nectar                          27
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        22
Chips and Tomatillo-Red Chili Salsa       20
Izze                                      20
Veggie Salad Bowl                         18
Chips and Roasted Chili-Corn Salsa        18
Barbacoa Crispy Tacos                     11
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Carnitas Crispy Tacos                      7
Veggie Soft Tacos                          7
Burrito                                    6
Veggie Salad                               6
Carnitas Salad Bowl                        6
Steak Salad                                4
Bowl                                       2
Salad                                      2
Crispy Tacos                               2
Chips and Mild Fresh Tomato Salsa          1
Carnitas Salad                             1
Veggie Crispy Tacos                        1
dtype: int64

## 26. Calculate the total quantity sold for each product.

In [73]:
chipo.groupby('item_name')['quantity'].sum()

item_name
6 Pack Soft Drink                         55
Barbacoa Bowl                             66
Barbacoa Burrito                          91
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Barbacoa Soft Tacos                       25
Bottled Water                            211
Bowl                                       4
Burrito                                    6
Canned Soda                              126
Canned Soft Drink                        351
Carnitas Bowl                             71
Carnitas Burrito                          60
Carnitas Crispy Tacos                      8
Carnitas Salad                             1
Carnitas Salad Bowl                        6
Carnitas Soft Tacos                       40
Chicken Bowl                             761
Chicken Burrito                          591
Chicken Crispy Tacos                      50
Chicken Salad                              9
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Chips                                    230
Chips and Fresh Tomato Salsa             130
Chips and Guacamole                      506
Chips and Mild Fresh Tomato Salsa          1
Chips and Roasted Chili Corn Salsa        23
Chips and Roasted Chili-Corn Salsa        18
Chips and Tomatillo Green Chili Salsa     45
Chips and Tomatillo Red Chili Salsa       50
Chips and Tomatillo-Green Chili Salsa     33
Chips and Tomatillo-Red Chili Salsa       25
Crispy Tacos                               2
Izze                                      20
Nantucket Nectar                          29
Salad                                      2
Side of Chips                            110
Steak Bowl                               221
Steak Burrito                            386
Steak Crispy Tacos                        36
Steak Salad                                4
Steak Salad Bowl                          31
Steak Soft Tacos                          56
Veggie Bowl                               87
Veggie Burrito                            97
Veggie Crispy Tacos                        1
Veggie Salad                               6
Veggie Salad Bowl                         18
Veggie Soft Tacos                          8
Name: quantity, dtype: int64

## 27. What is the average quantity of items per order?

In [76]:
chipo.groupby('order_id')['quantity'].mean()

order_id
1       1.0
2       2.0
3       1.0
4       1.0
5       1.0
       ...
1830    1.0
1831    1.0
1832    1.0
1833    1.0
1834    1.0
Name: quantity, Length: 1834, dtype: float64

## 31. What was the most ordered item in the choice_description column?

In [90]:
chipo.groupby('choice_description')['quantity'].sum().sort_values(ascending=False).head(1)

choice_description
[Diet Coke]    159
Name: quantity, dtype: int64

## 32. What is the average revenue amount per order?

In [103]:
chipo['revenue'] = chipo['item_price']*chipo['quantity']
chipo.groupby('order_id')['revenue'].mean()

order_id
1        2.890000
2       33.960000
3        6.335000
4       10.500000
5        6.850000
          ...
1830    11.500000
1831     4.300000
1832     6.600000
1833    11.750000
1834     9.583333
Name: revenue, Length: 1834, dtype: float64

## 33. Which product has the highest total quantity sold?

In [91]:
chipo.groupby('item_name')['quantity'].sum().sort_values(ascending=False).head(1)

item_name
Chicken Bowl    761
Name: quantity, dtype: int64

## 34. Calculate the average price of each product.

In [92]:
chipo.groupby('item_name')['item_price'].mean()

item_name
6 Pack Soft Drink                         6.610185
Barbacoa Bowl                            10.187273
Barbacoa Burrito                          9.832418
Barbacoa Crispy Tacos                    10.928182
Barbacoa Salad Bowl                      10.640000
Barbacoa Soft Tacos                      10.018400
Bottled Water                             1.867654
Bowl                                     14.800000
Burrito                                   7.400000
Canned Soda                               1.320577
Canned Soft Drink                         1.457641
Carnitas Bowl                            10.833971
Carnitas Burrito                         10.132712
Carnitas Crispy Tacos                    11.137143
Carnitas Salad                            8.990000
Carnitas Salad Bowl                      11.056667
Carnitas Soft Tacos                       9.398500
Chicken Bowl                             10.113953
Chicken Burrito                          10.082857
Chicken Crispy Tacos                     10.045319
Chicken Salad                             9.010000
Chicken Salad Bowl                       11.170455
Chicken Soft Tacos                        9.635565
Chips                                     2.342844
Chips and Fresh Tomato Salsa              3.285091
Chips and Guacamole                       4.595073
Chips and Mild Fresh Tomato Salsa         3.000000
Chips and Roasted Chili Corn Salsa        3.084091
Chips and Roasted Chili-Corn Salsa        2.390000
Chips and Tomatillo Green Chili Salsa     3.087209
Chips and Tomatillo Red Chili Salsa       3.072917
Chips and Tomatillo-Green Chili Salsa     2.544194
Chips and Tomatillo-Red Chili Salsa       2.987500
Crispy Tacos                              7.400000
Izze                                      3.390000
Nantucket Nectar                          3.641111
Salad                                     7.400000
Side of Chips                             1.840594
Steak Bowl                               10.711801
Steak Burrito                            10.465842
Steak Crispy Tacos                       10.209714
Steak Salad                               8.915000
Steak Salad Bowl                         11.847931
Steak Soft Tacos                          9.746364
Veggie Bowl                              10.211647
Veggie Burrito                            9.839684
Veggie Crispy Tacos                       8.490000
Veggie Salad                              8.490000
Veggie Salad Bowl                        10.138889
Veggie Soft Tacos                        10.565714
Name: item_price, dtype: float64

## 35. Which choice appears most often?

In [104]:
chipo.groupby('choice_description')['quantity'].sum().sort_values(ascending = False).head(1)

choice_description
[Diet Coke]    159
Name: quantity, dtype: int64