In [32]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv('chipotle.tsv', sep = '\t')

In [33]:
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [34]:
df.shape

(4622, 5)

In [35]:
df.index

RangeIndex(start=0, stop=4622, step=1)

In [36]:
# df.select_dtypes(include = "object").columns
df.select_dtypes(exclude = "object").columns

Index(['order_id', 'quantity'], dtype='object')

In [37]:
df.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [38]:
df['item_price'] = df['item_price'].str.replace('$', '').astype(float)

In [40]:
df.head(5)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [51]:
df[df['item_price'] > 10].count()

order_id              1130
quantity              1130
item_name             1130
choice_description    1123
item_price            1130
dtype: int64

In [45]:
df.describe()

          order_id     quantity   item_price
count  4622.000000  4622.000000  4622.000000
mean    927.254868     1.075725     7.464336
std     528.890796     0.410186     4.245557
min       1.000000     1.000000     1.090000
25%     477.250000     1.000000     3.390000
50%     926.000000     1.000000     8.750000
75%    1393.000000     1.000000     9.250000
max    1834.000000    15.000000    44.250000

In [53]:
df[['item_name', 'item_price']]

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

In [56]:
df['item_price'].sort_values(ascending = False)

3598    44.25
3480    35.25
1254    35.00
3602    35.00
3601    33.75
        ...
3936     1.09
2922     1.09
1396     1.09
2562     1.09
1457     1.09
Name: item_price, Length: 4622, dtype: float64

In [57]:
df.sort_values(by = 'item_price', ascending = False)

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25
3480,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",35.25
1254,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",35.00
3602,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",35.00
3601,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",33.75
...,...,...,...,...,...
3936,1578,1,Canned Soda,[Diet Dr. Pepper],1.09
2922,1162,1,Bottled Water,NaN,1.09
1396,567,1,Canned Soda,[Coca Cola],1.09
2562,1014,1,Canned Soda,[Coca Cola],1.09
1457,591,1,Canned Soda,[Sprite],1.09

In [60]:
#What is the quantity of the most expensive item ordered?
df.sort_values(by = 'item_price', ascending = False).head(1)['quantity']

3598    15
Name: quantity, dtype: int64

In [68]:
# How many times did someone order more than one Canned Soda?

df[(df['item_name'] == 'Canned Soda') & (df['quantity'] > 1)]['quantity'].count()

np.int64(20)

In [70]:
df['item_name'].nunique()

50

In [80]:
df.groupby('item_name')['item_price'].mean()

item_name
6 Pack Soft Drink                         6.610185
Barbacoa Bowl                            10.187273
Barbacoa Burrito                          9.832418
Barbacoa Crispy Tacos                    10.928182
Barbacoa Salad Bowl                      10.640000
Barbacoa Soft Tacos                      10.018400
Bottled Water                             1.867654
Bowl                                     14.800000
Burrito                                   7.400000
Canned Soda                               1.320577
Canned Soft Drink                         1.457641
Carnitas Bowl                            10.833971
Carnitas Burrito                         10.132712
Carnitas Crispy Tacos                    11.137143
Carnitas Salad                            8.990000
Carnitas Salad Bowl                      11.056667
Carnitas Soft Tacos                       9.398500
Chicken Bowl                             10.113953
Chicken Burrito                          10.082857
Chicken Crispy Tacos                     10.045319
Chicken Salad                             9.010000
Chicken Salad Bowl                       11.170455
Chicken Soft Tacos                        9.635565
Chips                                     2.342844
Chips and Fresh Tomato Salsa              3.285091
Chips and Guacamole                       4.595073
Chips and Mild Fresh Tomato Salsa         3.000000
Chips and Roasted Chili Corn Salsa        3.084091
Chips and Roasted Chili-Corn Salsa        2.390000
Chips and Tomatillo Green Chili Salsa     3.087209
Chips and Tomatillo Red Chili Salsa       3.072917
Chips and Tomatillo-Green Chili Salsa     2.544194
Chips and Tomatillo-Red Chili Salsa       2.987500
Crispy Tacos                              7.400000
Izze                                      3.390000
Nantucket Nectar                          3.641111
Salad                                     7.400000
Side of Chips                             1.840594
Steak Bowl                               10.711801
Steak Burrito                            10.465842
Steak Crispy Tacos                       10.209714
Steak Salad                               8.915000
Steak Salad Bowl                         11.847931
Steak Soft Tacos                          9.746364
Veggie Bowl                              10.211647
Veggie Burrito                            9.839684
Veggie Crispy Tacos                       8.490000
Veggie Salad                              8.490000
Veggie Salad Bowl                        10.138889
Veggie Soft Tacos                        10.565714
Name: item_price, dtype: float64