<h1 align = 'center'>Probability and Bayes Theorem</h1>

<hr>

<h2 align = 'center'>Part 1: Probability</h2>

<hr>

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('credit_card.csv')
print(df.shape)

(41188, 10)

In [2]:
df.head(5)

,gender,age,job,marital,education,default,housing,loan,contact,CreditCard
0,female,56,housemaid,married,basic.4y,no,no,no,telephone,no
1,male,57,services,married,high.school,yes,no,no,telephone,no
2,female,37,services,married,high.school,no,yes,no,telephone,no
3,female,40,admin.,married,basic.6y,no,no,no,telephone,no
4,female,56,services,married,high.school,no,no,yes,telephone,no

In [3]:
df.describe()

               age
count  41188.00000
mean      40.02406
std       10.42125
min       17.00000
25%       32.00000
50%       38.00000
75%       47.00000
max       98.00000

In [4]:
df.describe(include = ['object', 'category'])

,gender,job,marital,education,default,housing,loan,contact,CreditCard
count,41188,41188,41188,41188,41188,41188,41188,41188,41188
unique,2,12,4,8,2,2,2,2,2
top,female,admin.,married,university.degree,no,yes,no,cellular,no
freq,20798,10422,24928,12168,32588,22566,33950,26144,36548

### Q1: What is the Probability that the Customer has a Credit Card ?

In [5]:
#total number of customers
total = df.shape[0]
#number of customers who has credit card
card = df[df['CreditCard'] == 'yes']
count_card = len(card)
#probab
p = round(count_card/total, 3) * 100
print(f'{p}%')

11.3%

### Q2: What is the Probability that the Customer age is greater than 50 ?

In [6]:
great_50 = df[df['age']>50]
count_card = len(great_50)
#probab
p_great_50 = round(count_card/total, 3) * 100
print(f'{p_great_50}%')

17.4%

### Q3: What is the probability that the customer is illiterate?

In [7]:
# illiter = df[df['education'] ]
illiter = df['education'].value_counts()['illiterate']
#probab
p_illi = round(illiter/total, 4) * 100
print(f'{p_illi}%')

0.04%

### Q4: What is the Probability that the Customer has a Telephone ?

In [8]:
tel = df[df['contact'] == 'telephone']
count_tel = len(tel)
#probab
p_tel = round(count_tel/total, 3) * 100
print(f'{p_tel}%')

36.5%

### Q5: What is the Probability that the Customer is Single and has a Credit Card ?

In [9]:
pd.crosstab(df['marital'], df['CreditCard'], margins=True)

CreditCard     no   yes    All
marital
divorced     4136   476   4612
married     22396  2532  24928
single       9948  1620  11568
unknown        68    12     80
All         36548  4640  41188

In [10]:
sngl_card = 1620
p_sngl_card = round(sngl_card/total, 3) * 100
print(f'{p_sngl_card}%')

3.9%

### Q6: What is the Probability that the Customer is Male and has at most 6 Year of Education ?

In [11]:
male_6_edu = df[(df['gender'] == 'male') & (df['education'] == 'basic.6y')]
count_male_6_edu = len(male_6_edu)
#probab
p_male_6_edu = round(count_male_6_edu/total, 3) * 100
print(f'{p_male_6_edu}%')

2.7%

### Q7: What is the Probability that the Customer is Retired and is divorced ?

In [12]:
rtrd_div = df[(df['marital'] == 'divorced') & (df['job'] == 'retired')]
count_rtrd_div = len(rtrd_div)
#probab
p_rtrd_div = round(count_rtrd_div/total, 3) * 100
print(f'{p_rtrd_div}%')

0.8%

### Q8: Given the Customer has the credit card, find the probability that he/she is married ?

In [13]:
pd.crosstab(df['marital'], df['CreditCard'], margins=True)

CreditCard     no   yes    All
marital
divorced     4136   476   4612
married     22396  2532  24928
single       9948  1620  11568
unknown        68    12     80
All         36548  4640  41188

In [14]:
p_AnB = 2532
p_B = 4640
print(round(p_AnB/p_B, 3))

0.546

### Q9: If a customer has a management job, find the probability that he has a housing

In [15]:
pd.crosstab(df['job'], df['housing'], margins = True)

housing           no    yes    All
job
admin.          4636   5786  10422
blue-collar     4304   4950   9254
entrepreneur     641    815   1456
housemaid        491    569   1060
management      1363   1561   2924
retired          784    936   1720
self-employed    641    780   1421
services        1818   2151   3969
student          381    494    875
technician      2980   3763   6743
unemployed       430    584   1014
unknown          153    177    330
All            18622  22566  41188

In [16]:
manage = 2924
manage_house = 1561
#probab
p_manage_house = round(manage_house/manage, 3) * 100
print(f'{p_manage_house}%')

53.400000000000006%

<hr>

<h2 align = 'center'>Part 2: Bayes Theorem</h2>

<hr>

### Kerala Flood Data

Data of monthly rainfall in Kerala from 1901 to 2018 is provided. It also contains information of floods.

### Columns in the Dataset:
- YEAR: Year between 1901 to 2018
- JAN, FEB,..., DEC:Rainfall in mm in the specified month
- ANNUAL RAINFALL: Total rainfall in mm in that year
- FLOODS: YES or NO, in that year

In [17]:
df = pd.read_csv('kerala_floods.csv')
df.shape

(118, 16)

In [18]:
df.head()

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL RAINFALL,FLOODS
0,KERALA,1901,28.7,44.7,51.6,160.0,174.7,824.6,743.0,357.5,197.7,266.9,350.8,48.4,3248.6,YES
1,KERALA,1902,6.7,2.6,57.3,83.9,134.5,390.9,1205.0,315.8,491.6,358.4,158.3,121.5,3326.6,YES
2,KERALA,1903,3.2,18.6,3.1,83.6,249.7,558.6,1022.5,420.2,341.8,354.1,157.0,59.0,3271.2,YES
3,KERALA,1904,23.7,3.0,32.2,71.5,235.7,1098.2,725.5,351.8,222.7,328.1,33.9,3.3,3129.7,YES
4,KERALA,1905,1.2,22.3,9.4,105.9,263.3,850.2,520.5,293.6,217.2,383.5,74.4,0.2,2741.6,NO

In [19]:
df.isnull().sum()

SUBDIVISION         0
YEAR                0
JAN                 0
FEB                 0
MAR                 0
APR                 0
MAY                 0
JUN                 0
JUL                 0
AUG                 0
SEP                 0
OCT                 0
NOV                 0
DEC                 0
 ANNUAL RAINFALL    0
FLOODS              0
dtype: int64

### We need to use Bays Therorm to calculate the probability of having a rainfall more than 500 mm in month of June, provided it has flooded in that year ?

1 - We may start by preparing the required columns:
- Create a new column named "June_more_than_500" and assign a value of 1 if the amount is more than 500 and 0 if it is less
than 500.
- Do the same for the 'FLOODS' column, assigning 1 for 'yes' and 0 for 'no'.

In [20]:
df['June_more_than_500'] = (df['JUL']>500).astype('int')
df['FLOODS'] = df['FLOODS'].map({"YES":1,"NO":0})
df.head()

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL RAINFALL,FLOODS,June_more_than_500
0,KERALA,1901,28.7,44.7,51.6,160.0,174.7,824.6,743.0,357.5,197.7,266.9,350.8,48.4,3248.6,1,1
1,KERALA,1902,6.7,2.6,57.3,83.9,134.5,390.9,1205.0,315.8,491.6,358.4,158.3,121.5,3326.6,1,1
2,KERALA,1903,3.2,18.6,3.1,83.6,249.7,558.6,1022.5,420.2,341.8,354.1,157.0,59.0,3271.2,1,1
3,KERALA,1904,23.7,3.0,32.2,71.5,235.7,1098.2,725.5,351.8,222.7,328.1,33.9,3.3,3129.7,1,1
4,KERALA,1905,1.2,22.3,9.4,105.9,263.3,850.2,520.5,293.6,217.2,383.5,74.4,0.2,2741.6,0,1

2 - Select only the columns that will help to answer the main question.

In [21]:
df2 = df[['YEAR', 'FLOODS', 'June_more_than_500']]
df2.head()

   YEAR  FLOODS  June_more_than_500
0  1901       1                   1
1  1902       1                   1
2  1903       1                   1
3  1904       1                   1
4  1905       0                   1

3- Create a cross tabulation for 'FLOODS' and 'June_more_than_500'

In [32]:
pd.crosstab(df2['June_more_than_500'], df2['FLOODS'], margins = True)

FLOODS               0   1  All
June_more_than_500
0                   19   3   22
1                   39  57   96
All                 58  60  118

4- What is the probability of a rainfall more than 500mm in June?

In [23]:
p_A = 96/118
p_A

0.8135593220338984

5- What is the probability of having a flood?

In [24]:
p_B = 60/118
p_B

0.5084745762711864

6- What is the probability of having a flood and a rainfall more than 500mm in June?

In [25]:
p_A_and_B = 57/118
p_A_and_B

0.4830508474576271

7- What is the Probability of having a flood given it rained more than 500mm in June?

In [26]:
p_B_given_A = p_A_and_B/p_A
p_B_given_A

0.59375

8- What is the probability of a rainfall less than 500mm in June?

In [27]:
p_not_A = 22/118
p_not_A

0.1864406779661017

9- What is probability of having a flood given that it rained less than 500mm?

In [40]:
p_B_given_not_A = 3/22
p_B_given_not_A

0.13636363636363635

10- Answer this question by using Bayes Theorem and the law of the Total Probaility

In [41]:
p_A_given_B = (p_B_given_A * p_A) / (p_B_given_A * p_A + p_B_given_not_A * p_not_A)
p_A_given_B

0.95

11- Answer this question by using Bayes Theorem only.

In [42]:
p_A_given_B = p_B_given_A * p_A / p_B
p_A_given_B

0.9500000000000002