<h1 align = center>Assignment_2_filtering_sorting</h1>

In [2]:
import pandas as pd

### 1. Load the (SuperMarket Analysis.csv) dataset and display the first 5 rows.

In [3]:
path = "SuperMarket Analysis.csv"

sales = pd.read_csv(path)

sales.head(5)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

### 2. Display the dataset shape (rows and columns).

In [7]:
sales.shape

(1000, 17)

### 3. List all column names.

In [8]:
sales.columns

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Sales', 'Date',
       'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income',
       'Rating'],
      dtype='object')

### 4. Identify categorical and numerical columns.

In [9]:
categorical_cols = sales.select_dtypes(include="object").columns
numerical_cols = sales.select_dtypes(exclude="object").columns

print(categorical_cols)
print(numerical_cols)

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Date', 'Time', 'Payment'],
      dtype='object')
Index(['Unit price', 'Quantity', 'Tax 5%', 'Sales', 'cogs',
       'gross margin percentage', 'gross income', 'Rating'],
      dtype='object')

### 5. Check for missing values in each column.

In [10]:
sales.isnull().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Sales                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

### 6. Display the data types of each column.

In [13]:
sales.dtypes

Invoice ID                  object
Branch                      object
City                        object
Customer type               object
Gender                      object
Product line                object
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Sales                      float64
Date                        object
Time                        object
Payment                     object
cogs                       float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

### 7.Show summary statistics for numerical columns (use pandas method).

In [18]:
sales.describe()

,Unit price,Quantity,Tax 5%,Sales,cogs,gross margin percentage,gross income,Rating
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1.000000e+03,1000.000000,1000.00000
mean,55.672130,5.510000,15.379369,322.966749,307.58738,4.761905e+00,15.379369,6.97270
std,26.494628,2.923431,11.708825,245.885335,234.17651,6.131498e-14,11.708825,1.71858
min,10.080000,1.000000,0.508500,10.678500,10.17000,4.761905e+00,0.508500,4.00000
25%,32.875000,3.000000,5.924875,124.422375,118.49750,4.761905e+00,5.924875,5.50000
50%,55.230000,5.000000,12.088000,253.848000,241.76000,4.761905e+00,12.088000,7.00000
75%,77.935000,8.000000,22.445250,471.350250,448.90500,4.761905e+00,22.445250,8.50000
max,99.960000,10.000000,49.650000,1042.650000,993.00000,4.761905e+00,49.650000,10.00000

### 8.Filter rows where Sales > 500.

In [25]:
sales[sales['Sales'] > 500]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,6:30:00 PM,Ewallet,597.73,4.761905,29.8865,4.1
7,315-22-5665,Giza,Naypyitaw,Member,Female,Home and lifestyle,73.56,10,36.7800,772.3800,2/24/2019,11:38:00 AM,Ewallet,735.60,4.761905,36.7800,8.0
14,829-34-3910,Alex,Yangon,Member,Female,Health and beauty,71.38,10,35.6900,749.4900,3/29/2019,7:21:00 PM,Cash,713.80,4.761905,35.6900,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
988,267-62-7380,Giza,Naypyitaw,Member,Male,Electronic accessories,82.34,10,41.1700,864.5700,3/29/2019,7:12:00 PM,Ewallet,823.40,4.761905,41.1700,4.3
989,430-53-4718,Cairo,Mandalay,Member,Male,Health and beauty,75.37,8,30.1480,633.1080,1/28/2019,3:46:00 PM,Credit card,602.96,4.761905,30.1480,8.4
991,602-16-6955,Cairo,Mandalay,Normal,Female,Sports and travel,76.60,10,38.3000,804.3000,1/24/2019,6:10:00 PM,Ewallet,766.00,4.761905,38.3000,6.0
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

### 9. Filter sales in City = “Yangon” and Sales > 200.

In [30]:
sales[(sales['City'] == 'Yangon') & (sales['Sales'] > 200)]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
6,355-53-5943,Alex,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,2:36:00 PM,Ewallet,413.04,4.761905,20.6520,5.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,221-25-5073,Alex,Yangon,Normal,Female,Food and beverages,74.66,4,14.9320,313.5720,3/4/2019,10:39:00 AM,Cash,298.64,4.761905,14.9320,8.5
981,809-46-1866,Alex,Yangon,Normal,Male,Health and beauty,58.15,4,11.6300,244.2300,1/23/2019,5:44:00 PM,Cash,232.60,4.761905,11.6300,8.4
982,139-32-4183,Alex,Yangon,Member,Female,Sports and travel,97.48,9,43.8660,921.1860,3/14/2019,2:19:00 PM,Ewallet,877.32,4.761905,43.8660,7.4
990,886-18-2897,Alex,Yangon,Normal,Female,Food and beverages,56.56,5,14.1400,296.9400,3/22/2019,7:06:00 PM,Credit card,282.80,4.761905,14.1400,4.5
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

### 10. Sort all orders by Sales in descending order.

In [32]:
sales.sort_values(by = 'Sales', ascending = False)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
350,860-79-0874,Giza,Naypyitaw,Member,Female,Fashion accessories,99.30,10,49.6500,1042.6500,2/15/2019,2:53:00 PM,Credit card,993.00,4.761905,49.6500,6.6
167,687-47-8271,Alex,Yangon,Normal,Male,Fashion accessories,98.98,10,49.4900,1039.2900,2/8/2019,4:20:00 PM,Credit card,989.80,4.761905,49.4900,8.7
557,283-26-5248,Giza,Naypyitaw,Member,Female,Food and beverages,98.52,10,49.2600,1034.4600,1/30/2019,8:23:00 PM,Ewallet,985.20,4.761905,49.2600,4.5
699,751-41-9720,Giza,Naypyitaw,Normal,Male,Home and lifestyle,97.50,10,48.7500,1023.7500,1/12/2019,4:18:00 PM,Ewallet,975.00,4.761905,48.7500,8.0
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402,236-86-3015,Giza,Naypyitaw,Member,Male,Home and lifestyle,13.98,1,0.6990,14.6790,2/4/2019,1:38:00 PM,Ewallet,13.98,4.761905,0.6990,9.8
443,192-98-7397,Giza,Naypyitaw,Normal,Male,Fashion accessories,12.78,1,0.6390,13.4190,1/8/2019,2:11:00 PM,Ewallet,12.78,4.761905,0.6390,9.5
223,279-62-1445,Giza,Naypyitaw,Member,Female,Fashion accessories,12.54,1,0.6270,13.1670,2/21/2019,12:38:00 PM,Cash,12.54,4.761905,0.6270,8.2
629,308-39-1707,Alex,Yangon,Normal,Female,Fashion accessories,12.09,1,0.6045,12.6945,1/26/2019,6:19:00 PM,Credit card,12.09,4.761905,0.6045,8.2
822,784-21-9238,Giza,Naypyitaw,Member,Male,Sports and travel,10.17,1,0.5085,10.6785,2/7/2019,2:15:00 PM,Cash,10.17,4.761905,0.5085,5.9

### 11. Sort by Date (ascending) and then Time (ascending).

In [33]:
sales.sort_values(by = ['Date', 'Time'], ascending = [True, False])

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
696,182-52-7000,Alex,Yangon,Member,Female,Sports and travel,27.04,4,5.4080,113.5680,1/1/2019,8:26:00 PM,Ewallet,108.16,4.761905,5.4080,6.9
484,493-65-6248,Giza,Naypyitaw,Member,Female,Sports and travel,36.98,10,18.4900,388.2900,1/1/2019,7:48:00 PM,Credit card,369.80,4.761905,18.4900,7.0
856,770-42-8960,Cairo,Mandalay,Normal,Male,Food and beverages,21.12,8,8.4480,177.4080,1/1/2019,7:31:00 PM,Cash,168.96,4.761905,8.4480,6.3
450,891-01-7034,Cairo,Mandalay,Normal,Female,Electronic accessories,74.71,6,22.4130,470.6730,1/1/2019,7:07:00 PM,Cash,448.26,4.761905,22.4130,6.7
496,556-97-7101,Giza,Naypyitaw,Normal,Female,Electronic accessories,63.22,2,6.3220,132.7620,1/1/2019,3:51:00 PM,Cash,126.44,4.761905,6.3220,8.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
393,308-47-4913,Alex,Yangon,Member,Female,Sports and travel,52.26,10,26.1300,548.7300,3/9/2019,12:45:00 PM,Credit card,522.60,4.761905,26.1300,6.2
626,816-57-2053,Alex,Yangon,Normal,Male,Sports and travel,60.87,2,6.0870,127.8270,3/9/2019,12:37:00 PM,Ewallet,121.74,4.761905,6.0870,8.7
611,277-35-5865,Giza,Naypyitaw,Member,Female,Food and beverages,98.97,9,44.5365,935.2665,3/9/2019,11:23:00 AM,Cash,890.73,4.761905,44.5365,6.7
729,299-29-0180,Cairo,Mandalay,Member,Female,Home and lifestyle,52.18,7,18.2630,383.5230,3/9/2019,10:54:00 AM,Cash,365.26,4.761905,18.2630,9.3
84,360-39-5055,Giza,Naypyitaw,Member,Female,Sports and travel,48.91,5,12.2275,256.7775,3/9/2019,10:17:00 AM,Cash,244.55,4.761905,12.2275,6.6

### 12.Sort by Unit price and Quantity.

In [35]:
sales.sort_values(by = ['Unit price', 'Quantity'], ascending = [True, True])

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
944,333-23-2632,Alex,Yangon,Member,Male,Health and beauty,10.08,7,3.5280,74.0880,3/28/2019,8:14:00 PM,Cash,70.56,4.761905,3.5280,4.2
572,239-48-4278,Alex,Yangon,Member,Male,Food and beverages,10.13,7,3.5455,74.4555,3/10/2019,7:35:00 PM,Ewallet,70.91,4.761905,3.5455,8.3
784,516-77-6464,Giza,Naypyitaw,Member,Female,Health and beauty,10.16,5,2.5400,53.3400,2/24/2019,1:08:00 PM,Ewallet,50.80,4.761905,2.5400,4.1
822,784-21-9238,Giza,Naypyitaw,Member,Male,Sports and travel,10.17,1,0.5085,10.6785,2/7/2019,2:15:00 PM,Cash,10.17,4.761905,0.5085,5.9
881,115-38-7388,Giza,Naypyitaw,Member,Female,Fashion accessories,10.18,8,4.0720,85.5120,3/30/2019,12:51:00 PM,Credit card,81.44,4.761905,4.0720,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283,667-92-0055,Alex,Yangon,Member,Male,Health and beauty,99.83,6,29.9490,628.9290,3/4/2019,3:02:00 PM,Ewallet,598.98,4.761905,29.9490,8.5
494,437-53-3084,Cairo,Mandalay,Normal,Male,Fashion accessories,99.89,2,9.9890,209.7690,2/26/2019,11:48:00 AM,Ewallet,199.78,4.761905,9.9890,7.1
930,641-62-7288,Cairo,Mandalay,Normal,Male,Home and lifestyle,99.92,6,29.9760,629.4960,3/24/2019,1:33:00 PM,Ewallet,599.52,4.761905,29.9760,7.1
983,148-41-7930,Giza,Naypyitaw,Normal,Male,Health and beauty,99.96,7,34.9860,734.7060,1/23/2019,10:33:00 AM,Cash,699.72,4.761905,34.9860,6.1
122,219-22-9386,Cairo,Mandalay,Member,Female,Sports and travel,99.96,9,44.9820,944.6220,3/9/2019,5:26:00 PM,Credit card,899.64,4.761905,44.9820,4.2

### 13. Calculate the total sales in “Sales” per Branch.

In [38]:
sales.groupby('Branch')['Sales'].sum()

Branch
Alex     106200.3705
Cairo    106197.6720
Giza     110568.7065
Name: Sales, dtype: float64

### 14. Calculate average Sales per City.

In [39]:
sales.groupby('City')['Sales'].mean()

City
Mandalay     319.872506
Naypyitaw    337.099715
Yangon       312.354031
Name: Sales, dtype: float64

### 15. Find the quantities sold per product line.

In [44]:
sales.groupby('Product line')['Quantity'].sum()

Product line
Electronic accessories    971
Fashion accessories       902
Food and beverages        952
Health and beauty         854
Home and lifestyle        911
Sports and travel         920
Name: Quantity, dtype: int64

### 16.Calculate average gross income per Gender.

In [45]:
sales.groupby('Gender')['gross income'].mean()

Gender
Female    16.234829
Male      14.240749
Name: gross income, dtype: float64

### 17. Count number of sales per Payment method.

In [46]:
sales.groupby('Payment')['Sales'].count()

Payment
Cash           344
Credit card    311
Ewallet        345
Name: Sales, dtype: int64

### 18.Find maximum Sales per Branch.

In [50]:
sales.groupby('Branch')['Sales'].max()

Branch
Alex     1039.29
Cairo    1022.49
Giza     1042.65
Name: Sales, dtype: float64

### 19. Find minimum Unit price per Product line.

In [49]:
sales.groupby('Product line')['Unit price'].min()

Product line
Electronic accessories    10.56
Fashion accessories       10.18
Food and beverages        10.13
Health and beauty         10.08
Home and lifestyle        10.53
Sports and travel         10.17
Name: Unit price, dtype: float64

### 20. Find the sum of gross income per Product line and Branch.

In [ ]:
sales.groupby(['Product line', 'Branch'])['gross income'].sum()

### 21. What is the total quantities sold in Product line: “Electronic accessories”?

In [57]:
sales.groupby('Product line')['Quantity'].sum()['Electronic accessories']

np.int64(971)

### 22. What is the average Sales for female customers?

In [58]:
sales.groupby('Gender')['Sales'].mean()['Female']

np.float64(340.9314141856392)

### 23. What is the most expensive Unit price among Customer type members only?

In [59]:
sales.groupby('Customer type')['Unit price'].max()['Member']

np.float64(99.96)

### 24. How many orders with Rating >= 9 ?

In [70]:
sales[sales['Rating'] >= 9.0]['tip'].count()

166

### 25. What is the total Sales for Payment “Credit card” in Branch Cairo?

In [80]:
sales.groupby(['Branch', 'Payment'])['Sales'].sum()['Cairo', 'Credit card']

np.float64(37344.8565)

In [ ]:
sales[(sales['City'] == 'Yang')]