<h1 style = 'text-align: center; color:red'> Week 2: EDA and Data Preprocessing</h1>

<hr>

<h2 style = 'text-align: center; color:green'>DATASET OVERVIEW</h2>

### 1. Importing the necessary libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

### 2. Importing the dataset

In [2]:
df = pd.read_csv("student-por.csv", sep=';', encoding='utf-8')
df.head(5)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

### 3. The dataset shape (rows and columns)

In [3]:
df.shape

(649, 33)

### 4. Column types

In [4]:
df.dtypes

school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64
dtype: object

##### Notes: There are 17 categorical columns that need to be encoded.

### 5. Checking for missing values in each column

In [5]:
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

##### Notes: There are no missing values.

### 6. Showing basic statistics for numerical columns

In [6]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000
mean,16.744222,2.514638,2.306626,1.568567,1.930663,0.221880,3.930663,3.180277,3.184900,1.502311,2.280431,3.536210,3.659476,11.399076,11.570108,11.906009
std,1.218138,1.134552,1.099931,0.748660,0.829510,0.593235,0.955717,1.051093,1.175766,0.924834,1.284380,1.446259,4.640759,2.745265,2.913639,3.230656
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,16.000000,2.000000,1.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,2.000000,0.000000,10.000000,10.000000,10.000000
50%,17.000000,2.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,2.000000,11.000000,11.000000,12.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,6.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,32.000000,19.000000,19.000000,19.000000

### 7. Showing basic statistics for categorical columns

In [7]:
df.describe(include = 'O')

,school,sex,address,famsize,Pstatus,Mjob,Fjob,reason,guardian,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic
count,649,649,649,649,649,649,649,649,649,649,649,649,649,649,649,649,649
unique,2,2,2,2,2,5,5,4,3,2,2,2,2,2,2,2,2
top,GP,F,U,GT3,T,other,other,course,mother,no,yes,no,no,yes,yes,yes,no
freq,423,383,452,457,569,258,367,285,455,581,398,610,334,521,580,498,410

### Summary
<h4>
The dataset contains 30 features. <br> There are 17 categorical columns that need to be encoded, while the remaining features are numeric or ordinal. <br> No missing values were found, simplifying preprocessing. <br> Our target variable is G3, the students’ final grade, which we aim to predict based on the other features.
</h4>

<hr>

<h2 style = 'text-align: center; color:green'>VISUALISATIONS</h2>

In [4]:
#fkjdk

<hr>

<h2 style = 'text-align: center; color:green'>MISSING VALUES & FEATURE ENGINEERING</h2>

### 1. Encoding categorical columns

In [21]:
#binary encoding

df['sex'] = df['sex'].map({'F': 0, 'M': 1})               #Female - 0, Male - 1
df['school'] = df['school'].map({'GP': 0, 'MS': 1})       #Gabriel Pereira - 0, Mousinho da Silveira - 1
df['address'] = df['address'].map({'U': 0, 'R': 1})       #urban - 0, rural - 1
df['famsize'] = df['famsize'].map({'LE3': 0, 'GT3':1})    #less than 3 - 0, greater than 3 - 1
df['Pstatus'] = df['Pstatus'].map({'T': 0, 'A': 1})       #living together - 0, apart - 1
df['schoolsup'] = df['schoolsup'].map({'yes': 1, 'no': 0}) 
df['famsup'] = df['famsup'].map({'yes': 1, 'no': 0})
df['paid'] = df['paid'].map({'yes': 1, 'no': 0})
df['activities'] = df['activities'].map({'yes': 1, 'no': 0})
df['nursery'] = df['nursery'].map({'yes': 1, 'no': 0})
df['higher'] = df['higher'].map({'yes': 1, 'no': 0})
df['internet'] = df['internet'].map({'yes': 1, 'no': 0})
df['romantic'] = df['romantic'].map({'yes': 1, 'no': 0})

##### Notes: Binary categorical variables were encoded as 0/1, where 1 indicates the presence of a feature.

In [9]:
# one-hot encoding

df = pd.get_dummies(df, columns=['Mjob', 'Fjob', 'reason', 'guardian'], drop_first=True).astype(int)

##### Notes:  Nominal categorical variables without an inherent order (Mjob, Fjob, reason, guardian) were transformed using one-hot encoding.

In [15]:
#checking the column types after the encoding

df.dtypes

school               int64
sex                  int64
age                  int64
address              int64
famsize              int64
Pstatus              int64
Medu                 int64
Fedu                 int64
traveltime           int64
studytime            int64
failures             int64
schoolsup            int64
famsup               int64
paid                 int64
activities           int64
nursery              int64
higher               int64
internet             int64
romantic             int64
famrel               int64
freetime             int64
goout                int64
Dalc                 int64
Walc                 int64
health               int64
absences             int64
G1                   int64
G2                   int64
G3                   int64
Mjob_health          int64
Mjob_other           int64
Mjob_services        int64
Mjob_teacher         int64
Fjob_health          int64
Fjob_other           int64
Fjob_services        int64
Fjob_teacher         int64
reason_home          int64
reason_other         int64
reason_reputation    int64
guardian_mother      int64
guardian_other       int64
dtype: object

In [17]:
# displaying the table after encoding

df.head(5)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,traveltime,studytime,...,Mjob_teacher,Fjob_health,Fjob_other,Fjob_services,Fjob_teacher,reason_home,reason_other,reason_reputation,guardian_mother,guardian_other
0,0,0,18,0,1,1,4,4,2,2,...,0,0,0,0,1,0,0,0,1,0
1,0,0,17,0,1,0,1,1,1,2,...,0,0,1,0,0,0,0,0,0,0
2,0,0,15,0,0,0,1,1,1,2,...,0,0,1,0,0,0,1,0,1,0
3,0,0,15,0,1,0,4,2,1,3,...,0,0,0,1,0,1,0,0,1,0
4,0,0,16,0,1,0,3,3,1,2,...,0,0,1,0,0,1,0,0,0,0

### Summary
<h4>
<br>Binary categorical features were mapped to 0/1. <br> Nominal categorical features without a natural order were converted into separate columns for each category using one-hot encoding to avoid introducing artificial ordinality. <br>Ordinal and numerical features were kept as integers. <br>These preprocessing steps ensure the dataset is ready for modeling.
</h4>

<hr>