<h1 align = 'center'>Assignment 9: Feature Scaling and Model Evaluation</h1>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer

from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler

from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score, mean_squared_error, mean_absolute_error
from sklearn.linear_model import LogisticRegression

## Q1: Feature Scaling Concepts
Instructions: Explain the following:
- Standardization
- Min-Max Scaling
- Robust scaling
- Why feature scaling is important.
<br> Write your answer below:

- Standardization is a scaling technique that transforms data so that it has a mean of 0 and a standard deviation of 1.
- Min-Max Scaling transforms features to a fixed range, usually between 0 and 1. It preserves the original distribution shape but compresses all values into a limited interval.
- Robust Scaling uses the median and IQR instead of mean and standard deviation.
- Feature scaling is important because many machine learning algorithms are sensitive to the magnitude of input features. If features are on different scales, models may become biased toward larger-valued variables.

<hr>

## Q2: Load and Explore Dataset
Instructions:
- Load the breast cancer dataset from sklearn.datas
- Display shape and first 5 rows

In [2]:
data = load_breast_cancer()

X = data.data
y = data.target
df = pd.DataFrame(data.data, columns = data.feature_names)
df['target'] = data.target
df.head(5)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

## Q3: Train-Test Split
Split data into training and testing sets (80/20)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42, stratify = y)

## Q4: Apply Feature Scaling
Apply:
- StandardScaler
- MinMaxScaler
- RobustScaler

In [4]:
minmax_scaler = MinMaxScaler()
standard_scaler = StandardScaler()
robust_scaler = RobustScaler()

X_train_minmax = minmax_scaler.fit_transform(X_train)
X_train_standard = standard_scaler.fit_transform(X_train)
X_train_robust = robust_scaler.fit_transform(X_train)

X_test_minmax = minmax_scaler.transform(X_test)
X_test_standard = standard_scaler.transform(X_test)
X_test_robust = robust_scaler.transform(X_test)

## Q5: Train Models
Train Logistic Regression on:
1. Unscaled data
2. Standardized scaled data
3. MinMax scaled data
4. Robust Scaled data

In [5]:
# Train unscaled data
model_raw = LogisticRegression(max_iter=5000)
model_raw.fit(X_train, y_train)
pred_raw = model_raw.predict(X_test)
acc_raw = accuracy_score(y_test, pred_raw)

# Train standardized scaled data
model_std = LogisticRegression(max_iter=5000)
model_std.fit(X_train_standard, y_train)
pred_std = model_std.predict(X_test_standard)
acc_std = accuracy_score(y_test, pred_std)

# Train MinMax scaled data
model_mm = LogisticRegression(max_iter=5000)
model_mm.fit(X_train_minmax, y_train)
pred_mm = model_mm.predict(X_test_minmax)
acc_mm = accuracy_score(y_test, pred_mm)

# Train Robust scaled data
model_rb = LogisticRegression(max_iter=5000)
model_rb.fit(X_train_robust, y_train)
pred_rb = model_rb.predict(X_test_robust)
acc_rb = accuracy_score(y_test, pred_rb)

## Q6: Evaluate Each Model
Evaluate each model using the corresponding test set and print the following:
- Accuracy
- MAE
- RMSE

In [6]:
# For unscaled data
mae_raw = mean_absolute_error(y_test, pred_raw)
rmse_raw = np.sqrt(mean_squared_error(y_test, pred_raw))

# For standardized scaled data
mae_std = mean_absolute_error(y_test, pred_std)
rmse_std = np.sqrt(mean_squared_error(y_test, pred_std))

# For MinMax scaled data
mae_mm = mean_absolute_error(y_test, pred_mm)
rmse_mm = np.sqrt(mean_squared_error(y_test, pred_mm))

# For Robust scaled data
mae_rb = mean_absolute_error(y_test, pred_rb)
rmse_rb = np.sqrt(mean_squared_error(y_test, pred_rb))

## Write down the results in a table (use markdown syntax for that). Use the following example as a guide

In [7]:
linreg = [{
    "Scaler type": "No Scaling",
    "Accuracy": acc_raw,
    "MAE": mae_raw,
    "RMSE": rmse_raw,
},{
    "Scaler type": "STD scaling",
    "Accuracy": acc_std,
    "MAE": mae_std,
    "RMSE": rmse_std,
},{
    "Scaler type": "MinMax Scaling",
    "Accuracy": acc_mm,
    "MAE": mae_mm,
    "RMSE": rmse_mm,
}, {
    "Scaler type": "Robust Scaling",
    "Accuracy": acc_rb,
    "MAE": mae_rb,
    "RMSE": rmse_rb,
}]

In [8]:
results = pd.DataFrame(linreg)
results

      Scaler type  Accuracy       MAE      RMSE
0      No Scaling  0.964912  0.035088  0.187317
1     STD scaling  0.982456  0.017544  0.132453
2  MinMax Scaling  0.956140  0.043860  0.209427
3  Robust Scaling  0.982456  0.017544  0.132453

## Q8: Reflection
Discuss:
- Impact of scaling on performance
- When scaling is necessary
  
Answer

- Feature scaling improved model performance compared to unscaled data. StandardScaler and RobustScaler achieved the best and identical results, suggesting that the dataset does not contain significant outliers.
- Feature scaling is necessary when features have different ranges or units, as it ensures that no feature dominates the learning process.